/* Answer key editor UI for Academy Admin */
(function(){
"use strict";
function bank(){try{return typeof window.__ACADEMY_GET_QUESTION_BANK__==="function"?window.__ACADEMY_GET_QUESTION_BANK__():null}catch{return null}}
function changed(){const b=bank();if(!b)return;try{window.AcademyQuestions&&window.AcademyQuestions.touch&&window.AcademyQuestions.touch(b)}catch{};try{window.changed&&window.changed()}catch{};try{window.updateQuestionSummary&&window.updateQuestionSummary()}catch{}}
function addStyle(){if(document.getElementById("ak-ui-style"))return;const s=document.createElement("style");s.id="ak-ui-style";s.textContent=".ak-box{margin:14px 0;padding:12px;border:1px solid #bfe3d5;border-radius:12px;background:#f2fbf7}.ak-box label{display:block;font-weight:700;margin-bottom:6px;color:#125d4d}.ak-box select,.ak-box textarea{width:100%}.ak-box small{display:block;margin-top:5px;color:#6c877f;font-size:10px}.ak-ok{color:#13735d!important;font-weight:700}.ak-warn{color:#a46122!important;font-weight:700}";document.head.appendChild(s)}
function render(){addStyle();const b=bank();if(!b||!Array.isArray(b.questions))return;const cards=[...document.querySelectorAll(".qb-card")];cards.forEach((card,i)=>{const q=b.questions[i];if(!q)return;card.querySelector(".ak-box")?.remove();const box=document.createElement("div");box.className="ak-box";if(q.type==="mcq"){const lab=document.createElement("label");lab.textContent="گزینه صحیح";const sel=document.createElement("select");const blank=document.createElement("option");blank.value="";blank.textContent="انتخاب گزینه صحیح…";sel.append(blank);const opts=Array.isArray(q.options)?q.options:[];opts.forEach((t,j)=>{const o=document.createElement("option");o.value=String(j);o.textContent=(j+1)+" — "+String(t||"");sel.append(o)});let idx=Number(q.correct_option_index);if(!Number.isInteger(idx)||idx<0||idx>=opts.length){const ca=String(q.correct_answer||"").trim();idx=ca?opts.findIndex(x=>String(x).trim()===ca):-1}if(idx>=0)sel.value=String(idx);const note=document.createElement("small");note.className=idx>=0?"ak-ok":"ak-warn";note.textContent=idx>=0?"گزینه صحیح انتخاب شده است.":"هنوز گزینه صحیح انتخاب نشده است.";sel.onchange=()=>{const n=sel.value===""?-1:Number(sel.value);q.correct_option_index=n;q.correct_answer=n>=0&&n<opts.length?String(q.options[n]):"";note.className=n>=0?"ak-ok":"ak-warn";note.textContent=n>=0?"گزینه صحیح انتخاب شد؛ با انتشار در شیت ثبت می‌شود.":"هنوز گزینه صحیح انتخاب نشده است.";changed()};box.append(lab,sel,note)}else{const lab=document.createElement("label");lab.textContent="پاسخ نمونه (تشریحی)";const ta=document.createElement("textarea");ta.rows=4;ta.placeholder="پاسخ نمونه یا نکات کلیدی مورد انتظار را بنویسید…";ta.value=String(q.sample_answer||"");const note=document.createElement("small");note.textContent="این پاسخ فقط برای کلید تصحیح ارسال می‌شود و در فرم شرکت‌کننده نمایش داده نمی‌شود.";ta.oninput=()=>{q.sample_answer=ta.value;changed()};box.append(lab,ta,note)}const body=card.querySelector(".qb-card-body")||card;const id=body.querySelector(".qb-id");id?body.insertBefore(box,id):body.appendChild(box)})}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;render()})}
new MutationObserver(m=>{if(m.some(x=>x.type==="childList"&&x.addedNodes.length))schedule()}).observe(document.body,{subtree:true,childList:true});
document.addEventListener("click",e=>{if(e.target.closest?.("[data-tab='questions'],#qb-fetch,.qb-card summary,.qb-add button"))setTimeout(schedule,0)});
setTimeout(render,250);
})();